-- Oracle PL/SQL solutions for PLSQL_Exercises.docx.
-- Run the supplied schema/sample-data script first.  This script adds the audit table.
ALTER TABLE Customers ADD (IsVIP CHAR(1) DEFAULT 'N' CHECK (IsVIP IN ('Y','N')));
CREATE TABLE AuditLog (audit_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  event_time DATE DEFAULT SYSDATE, transaction_id NUMBER, action VARCHAR2(30), details VARCHAR2(4000));
/

-- 1. Control structures
BEGIN
  FOR c IN (SELECT customerid FROM customers WHERE MONTHS_BETWEEN(SYSDATE,dob)/12 > 60) LOOP
    UPDATE loans SET interestrate = interestrate - 1 WHERE customerid = c.customerid;
  END LOOP;
END;
/
BEGIN
  -- A BOOLEAN cannot be stored in Oracle SQL; a CHAR(1) flag is used.
  FOR c IN (SELECT customerid, balance FROM customers) LOOP
    UPDATE customers SET isvip = CASE WHEN c.balance > 10000 THEN 'Y' ELSE 'N' END WHERE customerid=c.customerid;
  END LOOP;
END;
/
BEGIN
  FOR x IN (SELECT c.name, l.loanid, l.enddate FROM loans l JOIN customers c ON c.customerid=l.customerid
            WHERE l.enddate BETWEEN TRUNC(SYSDATE) AND TRUNC(SYSDATE)+30) LOOP
    DBMS_OUTPUT.PUT_LINE('Reminder: '||x.name||', loan '||x.loanid||' is due on '||TO_CHAR(x.enddate,'DD-MON-YYYY'));
  END LOOP;
END;
/

-- 2. Error handling
CREATE OR REPLACE PROCEDURE SafeTransferFunds(p_from NUMBER,p_to NUMBER,p_amount NUMBER) AS
  e_insufficient EXCEPTION; v_balance accounts.balance%TYPE;
BEGIN
  IF p_amount <= 0 THEN RAISE_APPLICATION_ERROR(-20001,'Amount must be positive'); END IF;
  SELECT balance INTO v_balance FROM accounts WHERE accountid=p_from FOR UPDATE;
  IF v_balance < p_amount THEN RAISE e_insufficient; END IF;
  UPDATE accounts SET balance=balance-p_amount,lastmodified=SYSDATE WHERE accountid=p_from;
  UPDATE accounts SET balance=balance+p_amount,lastmodified=SYSDATE WHERE accountid=p_to;
  COMMIT;
EXCEPTION WHEN e_insufficient THEN ROLLBACK; DBMS_OUTPUT.PUT_LINE('Transfer failed: insufficient funds');
  WHEN NO_DATA_FOUND THEN ROLLBACK; DBMS_OUTPUT.PUT_LINE('Transfer failed: account not found');
  WHEN OTHERS THEN ROLLBACK; DBMS_OUTPUT.PUT_LINE('Transfer failed: '||SQLERRM);
END;
/
CREATE OR REPLACE PROCEDURE UpdateSalary(p_employee_id NUMBER,p_percent NUMBER) AS
BEGIN
  UPDATE employees SET salary=salary*(1+p_percent/100) WHERE employeeid=p_employee_id;
  IF SQL%ROWCOUNT=0 THEN RAISE NO_DATA_FOUND; END IF; COMMIT;
EXCEPTION WHEN NO_DATA_FOUND THEN ROLLBACK; DBMS_OUTPUT.PUT_LINE('Employee '||p_employee_id||' does not exist');
  WHEN OTHERS THEN ROLLBACK; DBMS_OUTPUT.PUT_LINE(SQLERRM); END;
/
CREATE OR REPLACE PROCEDURE AddNewCustomer(p_id NUMBER,p_name VARCHAR2,p_dob DATE,p_balance NUMBER) AS
BEGIN
  INSERT INTO customers(customerid,name,dob,balance,lastmodified) VALUES(p_id,p_name,p_dob,p_balance,SYSDATE); COMMIT;
EXCEPTION WHEN DUP_VAL_ON_INDEX THEN ROLLBACK; DBMS_OUTPUT.PUT_LINE('Customer '||p_id||' already exists');
  WHEN OTHERS THEN ROLLBACK; DBMS_OUTPUT.PUT_LINE(SQLERRM); END;
/

-- 3. Stored procedures
CREATE OR REPLACE PROCEDURE ProcessMonthlyInterest AS BEGIN
  UPDATE accounts SET balance=balance*1.01,lastmodified=SYSDATE WHERE UPPER(accounttype)='SAVINGS'; COMMIT; END;
/
CREATE OR REPLACE PROCEDURE UpdateEmployeeBonus(p_department VARCHAR2,p_percent NUMBER) AS BEGIN
  UPDATE employees SET salary=salary*(1+p_percent/100) WHERE department=p_department; COMMIT; END;
/
CREATE OR REPLACE PROCEDURE TransferFunds(p_from NUMBER,p_to NUMBER,p_amount NUMBER) AS BEGIN
  SafeTransferFunds(p_from,p_to,p_amount); END;
/

-- 4. Functions
CREATE OR REPLACE FUNCTION CalculateAge(p_dob DATE) RETURN NUMBER IS BEGIN
  RETURN TRUNC(MONTHS_BETWEEN(SYSDATE,p_dob)/12); END;
/
CREATE OR REPLACE FUNCTION CalculateMonthlyInstallment(p_amount NUMBER,p_annual_rate NUMBER,p_years NUMBER) RETURN NUMBER IS
  r NUMBER:=p_annual_rate/1200; n NUMBER:=p_years*12;
BEGIN RETURN CASE WHEN r=0 THEN p_amount/n ELSE p_amount*r*POWER(1+r,n)/(POWER(1+r,n)-1) END; END;
/
CREATE OR REPLACE FUNCTION HasSufficientBalance(p_account_id NUMBER,p_amount NUMBER) RETURN BOOLEAN IS v_balance NUMBER;
BEGIN SELECT balance INTO v_balance FROM accounts WHERE accountid=p_account_id; RETURN v_balance>=p_amount;
EXCEPTION WHEN NO_DATA_FOUND THEN RETURN FALSE; END;
/

-- 5. Triggers
CREATE OR REPLACE TRIGGER UpdateCustomerLastModified BEFORE UPDATE ON customers FOR EACH ROW BEGIN :NEW.lastmodified:=SYSDATE; END;
/
CREATE OR REPLACE TRIGGER LogTransaction AFTER INSERT ON transactions FOR EACH ROW BEGIN
  INSERT INTO auditlog(transaction_id,action,details) VALUES(:NEW.transactionid,'INSERT','Transaction '||:NEW.transactiontype||' amount '||:NEW.amount); END;
/
CREATE OR REPLACE TRIGGER CheckTransactionRules BEFORE INSERT ON transactions FOR EACH ROW DECLARE v_balance NUMBER;
BEGIN
  IF :NEW.transactiontype='Deposit' AND :NEW.amount<=0 THEN RAISE_APPLICATION_ERROR(-20002,'Deposit must be positive'); END IF;
  IF :NEW.transactiontype='Withdrawal' THEN SELECT balance INTO v_balance FROM accounts WHERE accountid=:NEW.accountid FOR UPDATE;
    IF :NEW.amount<=0 OR :NEW.amount>v_balance THEN RAISE_APPLICATION_ERROR(-20003,'Invalid withdrawal'); END IF; END IF;
END;
/

-- 6. Explicit cursors
DECLARE CURSOR GenerateMonthlyStatements IS SELECT c.name,t.transactionid,t.amount,t.transactiontype FROM transactions t JOIN accounts a ON a.accountid=t.accountid JOIN customers c ON c.customerid=a.customerid WHERE TRUNC(t.transactiondate,'MM')=TRUNC(SYSDATE,'MM');
BEGIN FOR x IN GenerateMonthlyStatements LOOP DBMS_OUTPUT.PUT_LINE(x.name||': '||x.transactiontype||' '||x.amount); END LOOP; END;
/
DECLARE CURSOR ApplyAnnualFee IS SELECT accountid FROM accounts FOR UPDATE; c_fee CONSTANT NUMBER:=100;
BEGIN FOR x IN ApplyAnnualFee LOOP UPDATE accounts SET balance=balance-c_fee,lastmodified=SYSDATE WHERE CURRENT OF ApplyAnnualFee; END LOOP; COMMIT; END;
/
DECLARE CURSOR UpdateLoanInterestRates IS SELECT loanid,interestrate FROM loans FOR UPDATE;
BEGIN FOR x IN UpdateLoanInterestRates LOOP UPDATE loans SET interestrate=x.interestrate-0.25 WHERE CURRENT OF UpdateLoanInterestRates; END LOOP; COMMIT; END;
/

-- 7. Packages
CREATE OR REPLACE PACKAGE CustomerManagement AS PROCEDURE add_customer(p_id NUMBER,p_name VARCHAR2,p_dob DATE,p_balance NUMBER); PROCEDURE update_customer(p_id NUMBER,p_name VARCHAR2,p_dob DATE); FUNCTION get_balance(p_id NUMBER) RETURN NUMBER; END;
/
CREATE OR REPLACE PACKAGE BODY CustomerManagement AS
 PROCEDURE add_customer(p_id NUMBER,p_name VARCHAR2,p_dob DATE,p_balance NUMBER) AS BEGIN AddNewCustomer(p_id,p_name,p_dob,p_balance); END;
 PROCEDURE update_customer(p_id NUMBER,p_name VARCHAR2,p_dob DATE) AS BEGIN UPDATE customers SET name=p_name,dob=p_dob WHERE customerid=p_id; END;
 FUNCTION get_balance(p_id NUMBER) RETURN NUMBER AS v NUMBER; BEGIN SELECT balance INTO v FROM customers WHERE customerid=p_id; RETURN v; END; END;
/
CREATE OR REPLACE PACKAGE EmployeeManagement AS PROCEDURE hire(p_id NUMBER,p_name VARCHAR2,p_position VARCHAR2,p_salary NUMBER,p_department VARCHAR2); PROCEDURE update_employee(p_id NUMBER,p_position VARCHAR2,p_salary NUMBER); FUNCTION annual_salary(p_id NUMBER) RETURN NUMBER; END;
/
CREATE OR REPLACE PACKAGE BODY EmployeeManagement AS
 PROCEDURE hire(p_id NUMBER,p_name VARCHAR2,p_position VARCHAR2,p_salary NUMBER,p_department VARCHAR2) AS BEGIN INSERT INTO employees VALUES(p_id,p_name,p_position,p_salary,p_department,SYSDATE); END;
 PROCEDURE update_employee(p_id NUMBER,p_position VARCHAR2,p_salary NUMBER) AS BEGIN UPDATE employees SET position=p_position,salary=p_salary WHERE employeeid=p_id; END;
 FUNCTION annual_salary(p_id NUMBER) RETURN NUMBER AS v NUMBER; BEGIN SELECT salary*12 INTO v FROM employees WHERE employeeid=p_id; RETURN v; END; END;
/
CREATE OR REPLACE PACKAGE AccountOperations AS PROCEDURE open_account(p_account NUMBER,p_customer NUMBER,p_type VARCHAR2,p_balance NUMBER); PROCEDURE close_account(p_account NUMBER); FUNCTION total_balance(p_customer NUMBER) RETURN NUMBER; END;
/
CREATE OR REPLACE PACKAGE BODY AccountOperations AS
 PROCEDURE open_account(p_account NUMBER,p_customer NUMBER,p_type VARCHAR2,p_balance NUMBER) AS BEGIN INSERT INTO accounts VALUES(p_account,p_customer,p_type,p_balance,SYSDATE); END;
 PROCEDURE close_account(p_account NUMBER) AS BEGIN DELETE FROM accounts WHERE accountid=p_account; END;
 FUNCTION total_balance(p_customer NUMBER) RETURN NUMBER AS v NUMBER; BEGIN SELECT NVL(SUM(balance),0) INTO v FROM accounts WHERE customerid=p_customer; RETURN v; END; END;
/
