import java.lang.reflect.*; import java.util.*; import java.util.concurrent.*;
// Java 21 exercises 29, 30, and 40, plus 37–39 and 41.
record Person(String name,int age) {} class RecordDemo { public static void main(String[]a){List<Person> people=List.of(new Person("Asha",22),new Person("Ravi",16));System.out.println(people.stream().filter(p->p.age()>=18).toList());} }
class PatternSwitch { static String describe(Object value){return switch(value){case Integer i->"Integer: "+i;case String s->"String: "+s;case Double d->"Double: "+d;case null->"null";default->"Other: "+value.getClass().getSimpleName();};} public static void main(String[]a){System.out.println(describe(10));System.out.println(describe("hello"));} }
class BytecodeTarget { int square(int n){return n*n;} public static void main(String[]a){System.out.println(new BytecodeTarget().square(4));} } // Inspect: javac ModernJava.java; javap -c BytecodeTarget
class DecompileTarget { public static void main(String[]a){System.out.println("Compile then open DecompileTarget.class with CFR or JD-GUI.");} }
class ReflectionTarget { public String greet(String name){return "Hello, "+name;} } class ReflectionDemo { public static void main(String[]a)throws Exception{Class<?> c=Class.forName("ReflectionTarget");Object o=c.getConstructor().newInstance();for(Method m:c.getDeclaredMethods())System.out.println(m.getName()+Arrays.toString(m.getParameterTypes()));System.out.println(c.getMethod("greet",String.class).invoke(o,"Ada"));} }
class VirtualThreads { public static void main(String[]a)throws InterruptedException{long start=System.nanoTime();List<Thread> ts=new ArrayList<>();for(int i=0;i<100_000;i++)ts.add(Thread.startVirtualThread(()->{}));for(Thread t:ts)t.join();System.out.printf("100,000 virtual threads finished in %.2f ms%n",(System.nanoTime()-start)/1e6);} }
class ExecutorCallable { public static void main(String[]a)throws Exception{ExecutorService pool=Executors.newFixedThreadPool(3);try{List<Future<Integer>> results=pool.invokeAll(List.of(()->1+1,()->2+2,()->3+3));for(Future<Integer> f:results)System.out.println(f.get());}finally{pool.shutdown();}} }
