import java.io.*; import java.util.*; import java.util.concurrent.*; import java.util.stream.*;
// Exercises 17–28
class Car { String make,model; int year; Car(String make,String model,int year){this.make=make;this.model=model;this.year=year;} void displayDetails(){System.out.printf("%d %s %s%n",year,make,model);} public static void main(String[]a){new Car("Toyota","Camry",2024).displayDetails();} }
class Animal { void makeSound(){System.out.println("Animal sound");} public static void main(String[]a){new Animal().makeSound();new Dog().makeSound();} } class Dog extends Animal { @Override void makeSound(){System.out.println("Bark");} }
interface Playable { void play(); } class Guitar implements Playable {public void play(){System.out.println("Guitar plays");}} class Piano implements Playable {public void play(){System.out.println("Piano plays");}} class PlayMusic {public static void main(String[]a){new Guitar().play();new Piano().play();}}
class DivisionTryCatch { public static void main(String[]a){Scanner s=new Scanner(System.in);try{System.out.println(s.nextInt()/s.nextInt());}catch(ArithmeticException e){System.out.println("Division by zero is not allowed.");}} }
class InvalidAgeException extends Exception { InvalidAgeException(String m){super(m);} } class AgeCheck { static void verify(int age)throws InvalidAgeException{if(age<18)throw new InvalidAgeException("Age must be at least 18");} public static void main(String[]a){try{verify(new Scanner(System.in).nextInt());System.out.println("Valid age");}catch(InvalidAgeException e){System.out.println(e.getMessage());}} }
class FileWrite { public static void main(String[]a)throws IOException{try(BufferedWriter w=new BufferedWriter(new FileWriter("output.txt"))){w.write(new Scanner(System.in).nextLine());}System.out.println("Data written.");} }
class FileRead { public static void main(String[]a)throws IOException{try(BufferedReader r=new BufferedReader(new FileReader("output.txt"))){r.lines().forEach(System.out::println);}} }
class StudentList { public static void main(String[]a){Scanner s=new Scanner(System.in);ArrayList<String> names=new ArrayList<>();while(s.hasNextLine()){String n=s.nextLine();if(n.isBlank())break;names.add(n);}names.forEach(System.out::println);} }
class StudentMap { public static void main(String[]a){Map<Integer,String> students=new HashMap<>();students.put(101,"Asha");students.put(102,"Ravi");System.out.println(students.get(new Scanner(System.in).nextInt()));} }
class ThreadDemo { public static void main(String[]a)throws InterruptedException{Runnable job=()->{for(int i=1;i<=3;i++)System.out.println(Thread.currentThread().getName()+" message "+i);};Thread one=new Thread(job,"one"),two=new Thread(job,"two");one.start();two.start();one.join();two.join();} }
class LambdaSort { public static void main(String[]a){List<String>x=new ArrayList<>(List.of("zebra","apple","mango"));x.sort((p,q)->p.compareTo(q));System.out.println(x);} }
class StreamEvens { public static void main(String[]a){List<Integer>evens=List.of(1,2,3,4,5,6).stream().filter(n->n%2==0).toList();System.out.println(evens);} }
